language: java
sudo: false
script: mvn install
deploy:
  provider: releases
  api_key:
    secure: st3Gq9LNc0hhb+ll/UmL6Y3hK1QdbSF3AA9tl2tJ4hqqubWZZcjiQzGzgOYjC4j2RuKtl6sIciWGn1tPpc84pjr1DtIHMdUTiF5NX9lIq2te933yS/jEZFbEVzyJFVbOz8kbV1ckKrekVy39yS0GdcyZt4j7geTpKBExWyt0328Pxvvt+tbH3WoACQuFm2LgHwea4I6C+LKDr3hSKT39kNt9Pg6ZZ1IIFVLGhf9i/OmNvAZeFM4CwPhLaoUpCjO66crT0ki27TaikzqDYzuT2ttTZg7kBM4mbfuL5mt5bDiPLrhIYfbF2HNthty/XNHJ7f8Fn+YAc9EZU2F1ohrOvybdlak4gz9/vZqFPLSKyGdvUw8SDNy2EXa4AzHEvsGLOhg5GDs+MVA8pWg5XwNkLa8XfcVhcdX/w4SAZGPmlCLq+Lb7FU5Mw/b7BTUHJhwlwY6nETrIJDr9NBk24ratKeupmsfUY+nqkjJmMYUHjfX5LTR4PcQzyO7+V607svF4dF23k24sMRle/g5V3tz6teVCpcS9bSdVsF8M9mUNvx0ZIxluC8nMmWtdOyXpe6DZmIE06PiOMSJNDUC4nWrLQ8Gl9VVnm6VhiSJS6llZnvregRwjJjAezmw787z54LlKdw/KPsjT3yGx+7vKBnl7muxFOJUABRi8Jkx8b5C1fso=
  file: "/home/travis/.m2/repository/ch/bbw/ConsoleCalculator/0.0.1-SNAPSHOT/1_ConsoleCalculator-0.0.1-SNAPSHOT.jar"
  on:
    repo: Erwond/ConsoleCalculatorWithMaven
