language: java
sudo: false
script: mvn install
deploy:
  provider: releases
  api_key:
    secure: kDsPAw8yRHf8vtqYadyenxPM6hGNsHVpkDlFAyuEsHueKy+kB/LsJgA6TRaVk5cEE0EQ3swzHJVpYs+7Lu8aS5eTzNOY3PfSVHpk5TBwz70LU2Qbj8n8cUI2YMTZyNrZEdorol8dvtZMn6PEed72V6m5z7+RCCF6kRY1vGERV0Z+6lIXtQAIMCYww+rtNa0Y9jBivhWsOyiXi4YMWa9UHU0bYnXpY7kvrhkHPaVsIc3dDB48J70Lb/NdXFceXbvyyUMFYlBGRh7C6sIGLmElJNdbbA1v+2goLfuP33sSYO3cqNMf00cyHJpNNOzJEvLKNv3RDhko1A2WcukmMSVyFzXjAG1RVb6E3YIh/IjWLqkI8P8hZpA6s7m2xGwddVY+XJodCJhFQ9TZ1Za6pEtM/+XhDheiYUJXhpbrM3uKAbm+uIdnOq5UXDQjmTypPl8H+IwtAw5i1JiWIPw7aEmQqx9+LwEQ8Xx+szEy3Fy1HX5NAx3fYPinnzZKYhLZzowUsd/B1eslD6QB8vWttMXs//2wS6oGpLDRfLSwCLZ2UdSMMizthhZ820q5twNiL+/BFIgh2kuvdeZ8m7gMYZuk34Pek9Q7rvXp3JFXUyiVFnIAvKZbzoayf9JGCRVj5IMW2TqCHlYU2ToAR/QOyN/17XI6HcO3NF2oQei1nMXUuvE=
  file: "/home/travis/.m2/repository/ch/bbw/02_ConsoleCalculatorWithMaven/0.0.1-SNAPSHOT/1_ConsoleCalculator-0.0.1-SNAPSHOT.jar"
  on:
    repo: Erwond/ConsoleCalculatorWithMaven
