language: java
sudo: false
script: mvn install
deploy:
  provider: releases
  api_key:
    secure: nu1RlacxyPDh45LJk9HEFX+WTabfF1YZJrELWqWFySYzyadUQjXwFws2EJPLXskJTjGqvT0ggRf3DwL+epEnmr5J+1uItrkWqQT7aRgwu08JlnRW3MqVdgmJBVF1YsbuowxUIiCkmfhmPyoeJnThQtZdm9iVf8WOVivGx0o6LK6KBEhFCtoE8lypWpxeo55eN4bdgJ8fMeP+A/qqA3LaMwEFSa98pdLQ355ojhQ3Ulb2cmrG3eVIwaZXZYI60bRObO6rLTUYzdqMHDHoJcxiZm6fBWMRDfQyWPtdaKvgKGHcJ7hQVgaKnkCBOISWXq4ajkOEHKuPd4BmTiqfg6nKt1qQQuFgA12/7VfGIqK1Gz8HTXrrMpbqOPfzQJJ4yM7EnQeUxb0MltZdwPymTjLiYuM6yrcd/jcpOBWZAqhm2gKYSqN+NvaOHUIS2YnHUlmRz9go3iH/DtSa7artipqX9ZLijaJU7Xp40obmACvN+17LKsPY8LZdnsz/pzuzPGswzbDqUBQXnlzQTrvtYWekkQXGFOc+Z44hyvBRrdqNj6VE6Unfs+SlcSdxmPFDzin8m/RNbllP2RVm3CqPb6EOzSmv3L/iSRHg2KLZrrsw14ESQQyQsSBCe9axmYH7fvUNSE+cH/oOZpcXuZH63a0dlHSeiE8A0IruXS0qsn2N7bE=
  file: ''
  on:
    repo: Erwond/ConsoleCalculatorWithMaven
