language: java
sudo: false
script: mvn install
deploy:
  provider: releases
  api_key:
    secure: QMhFEd0+y/tciOtSQPAQ3k9ZnzvqMdXxgtckrbMxObvLsiPRhBCdk5LnppeAsyLOYDVdlSeIiO1p06biWVl43JsWFxX0yvHMFnaAFIG6EsLQtoYOY3GBaVJH5sVOZVBDfpkUNbsAA7y8QJ7duQU83vSpCtG7R+sGHEmY5w2asK/aSdltMY+kZ0xG3RLrH8P6RepdJ4LspG5TJZlY0VI1en8C80g41lOmhDX/WzWfvdXtUBP3NhilHX27rwET5PiX1DaBwDhn17kAmo6QqZJLvKO0F2NEMeAHweBcbKVAKmDfcBAIJKVslmD7zH/lvGFVPDfZYtGeWY5pc6+9N7K+nP5PpQqu8VMYtwTE1dlTDqOcNCBVVDNYvcc43jIaIngN/HX3qBsgnZ08ZrIGc9s0lV7cmGU+mH3bgZ2p4gpKaC6WQu71d4ijDoTIydMoZ9xG3sqMqBACNtY5LdKnO5iOQTkFJBadCev1SgSIChOYTuvZZVH0ttMtewTPstNI4rlzOoDv9hov+uNV4OgTd/f4i35GKmcDMJ0/owwirbTFuFtNroSEomEjv2goBvZSLt1P95eyw3zNkI++2j97ubxjFSiHsSPvCkgEGTiBAhUdmK/v85dojdcQhtO6vdqEtQAaIetFK844kO+XMnwrN+VGv5n9GDXbuDyKreuT7jIK3gY=
  file: "\\home\\travis\\.m2\\repository\\ch\\bbw\\ConsoleCalculator\\0.0.1-SNAPSHOT\\1_ConsoleCalculator-0.0.1-SNAPSHOT.jar"
  on:
    repo: Erwond/ConsoleCalculatorWithMaven
